/**
 * @file 66AK2H14_link_binary_blob.c
 * @author Chester Gillon
 * @date 19-Apr-2019
 * @details
 *  Program which demonstrates how to get the GCC ARM objcopy to create an object containing the contents of binary blob
 *  into an object file which can be linked using the TI C6000 linker.
 *  The source code of this file is used as a blob which is linked into the program so the program can display its source.
 *
 *  The project setup steps were:
 *  1. Create a Linked Resource Path Variable named CG_GCC_ROOT with the following value:
 *       ${CCS_INSTALL_ROOT}/tools/compiler/gcc-arm-none-eabi-7-2017-q4-major
 *  2. Add the following pre-build step:
 *       ${CG_GCC_ROOT}/bin/arm-none-eabi-objcopy --alt-machine-code=140 --input-target=binary --output-target=elf32-little  ../66AK2H14_link_binary_blob.c 66AK2H14_link_binary_blob_elf.o
 *
 *     Where the alt-machine-code of 140 is the value for "TI C6x".
 *  3. Add the following linker libraries:
 *        66AK2H14_link_binary_blob_elf.o
 */

#include <stdint.h>
#include <stdio.h>

/* The symbols generated by the conversion of this source file into an object file */
extern char _binary____66AK2H14_link_binary_blob_c_start;
extern char _binary____66AK2H14_link_binary_blob_c_end;

int main(void)
{
    const size_t length = &_binary____66AK2H14_link_binary_blob_c_end - &_binary____66AK2H14_link_binary_blob_c_start;
    printf ("binary blob start address=0x%p\n", &_binary____66AK2H14_link_binary_blob_c_start);
    printf ("binary blob end address=0x%p\n", &_binary____66AK2H14_link_binary_blob_c_end);
    printf ("binary blob length=%u\n", length);
    printf ("binary blob contents:\n");
    fwrite (&_binary____66AK2H14_link_binary_blob_c_start, 1, length, stdout);
	return 0;
}
