/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      1200,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "TMS320TCI6638",
            externalMemoryMap: 
           [          
                ["DDR3", 
                     {
                        name: "DDR3",
                        base: 0x80000000,                    
                        len: 0x80000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
           ],
          l1DMode: "32k",
          l1PMode: "32k",
          l2Mode: "1024k",

    });
    
instance :
    
    override config string codeMemory  = "DDR3";   
    override config string dataMemory  = "DDR3";                                
    override config string stackMemory = "DDR3";

    config String l1DMode = "32k";
    config String l1PMode = "32k";
    config String l2Mode = "1024k";
}
