/* This file was automatically generated by generate_flash_constant_data.m */
#define FLASH_DATA_NUM_WORDS 235929
#define FLASH_DATA_INITIAL_SEED 4168664255
extern const uint32_t flash_constant_data[FLASH_DATA_NUM_WORDS];
